### ISSUE TITLE
Broken link in the readme

### ISSUE THREAD

**Issue by AZMindroma** [MikeJollie2707/MichaelBot#1]
Hello, dear MikeJollie.

A link to the INSTALLATION.md in the README.md has the link `"https://github.com/MikeJollie2707/MichaelBot/blob/master/docs/INSTALLATION.md",` although the actual INSTALLATION.md is at `/docs/docs/,` hence breaking the link.

**Comment by MikeJollie2707** [comment]
Will be fixed on the next push.
